# Accessing and Evaluating Scholarly Literature

## Overview {-}

In Unit 2, we will focus on gaining familiarity with various genres of scholarly literature, getting a sense of how these genres contribute to your own scholarly endeavours. Through first-hand experience you will begin locating, organizing and evaluating relevant scholarly literature. Two of the major assignments in this course hinge on your ability to conduct a review of precedent literature. Although these assignments are not due until the later in this course, our work in Unit 2 is the foundation for those assignments.  

## Topics {-}

Unit 2 is divided into 3 topics:

1. Accessing Scholarly Literature

2. Utilizing Scholarly Literature

3. Evaluating scholarly literature



## Learning Outcomes{-}

When you have completed this unit you should be able to:

1.  Employ different search strategies to locate different sources of scholarly literature.
2.  Evaluate the credibility and reliability of sources of scholarly literature.
3.  Document and synthesize key sources connecting them with the research question and topic area.



## Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.


| **Learning Activities** |
|----|
|**Activity:** Watch the video on accessing scholarly literature.  Read Chapters 2 and 4 in the Frederikson & Phelps text. Watch the tutorial "[Preparing a research question for a database search](https://vimeo.com/161998287/7661f12293). Follow the directions on searching for books through the TWU Library  |
|**Activity:** Reading Chapter 6 of the Fredericksen and Phelps (n.d.) text. Watch the videos on how to develop research skills. |
|**Activity:** Read chapter 6: Evaluating Sources in the Fredericksen and Phelps (n.d.) text. Watch the videos on using Google Scholar, assessing online resources and evaluating a journal article.   |
|**Assessment:** Contribute to the course discussions. See Assessment tab in Moodle for details. |
|**Assessment:**  Complete Assignment #1: Clarifying Your Research Interest.   |



## Resources{-}

Here are the resources you will need to complete the unit:

*   Frederiksen, L. & Phelps, S. F. (n.d.). Literature reviews for education and nursing graduate students. Retrieved from [https://press.rebus.community/literaturereviewsedunursing/](https://press.rebus.community/literaturereviewsedunursing/)
*   Video tutorials found at: [http://libguides.twu.ca/library\_research/home](http://libguides.twu.ca/library_research/home){target="_blank"}


## Accessing Scholarly Literature

In this unit you will be exploring the topic “Accessing and Evaluating Scholarly Literature”.  This unit will help you gain familiarity with various genres of scholarly literature and help you get a sense of what scholarly sources of information are available, given your own research interests.  In this unit you will also gain first-hand experience in locating and organizing and evaluating relevant scholarly literature.

The learning activities in this unit will walk you through some very practical readings and video tutorials on how to access and evaluate scholarly literature. Let's begin!

Accessing scholarly literature can be a frustrating process. The key is to start at the beginning with a good plan and keep yourself organized. Organizing tools are important both to streamline your literature search and to summarize and synthesize. As you begin your literature search (library books, online periodicals, internet search), organize your search into general topic areas and more specific keywords. It is very helpful to have some sense of the various fields that will potentially inform your research interests.

Part of your planning and organizing is to recognize various genres of scholarly literature and to be aware of the limitations inherent to each. A very helpful discussion is provided by Plano-Clark and Creswell (2015) on pages 10-12.

There are three different categories of documents where you can find research reports: summaries and books, journal articles and early stage materials such as conference presentations. Many times you will see this sequence followed: A research project is completed, and the research is first published in a Mater's thesis or PhD dissertation, or as a paper in a symposium or conference. The research report then goes to a professional journal for publication and eventually it is incorporated into a book. By the time a dissertation is successfully defended, the actual research may have been conducted two to three years earlier. It could easily take another three years for a journal article to make it through the peer-review process and be published. Therefore, the research referenced in the journal article could be at least five years old. It could easily take another five years for high quality publishers to work through their review processes and publish something in a book. Obviously, what you lose in this process is cutting edge thought.

The chart below summarizes the relative advantages and disadvantages of each genre of scholarly literature. You can refer to Plano-Clark and Creswell (2015) pages 10-12 for more details.

|Genre |	Advantages |	Disadvantages |	Utility|
|:---|:---|:---|:---|
|Summaries (encyclopedias and handbooks) |	Generally highest quality. |	Tend to be dated. |	Establish a general working knowledge of the field.|
|Books |	Generally high quality. |	Can be dated. |	Establish mainstream thought. Most foundational literature is found in books.|
|Journal Articles |	Generally high quality.* Provide a clear description of actual research. Generally more current than books or summaries. |	Generally will not give a full development of application and implications. |	Best available balance between quality and currency.|
|Early stage materials (conference papers, dissertations, newspapers, personal websites etc.) |	Most current cutting edge ideas are found here. |	Little review for quality (except for dissertations). Ideas are not usually well developed. |	Valuable for establishing trends in current thought. Use cautiously.|

```{block, type='caution'}
*Note:* High quality journals are determined by the peer review process, the journals impact factor (IF) and by professional reputation. The impact factor is a measure of the frequency with which the average article in a journal has been cited in a particular year. The IF is used to measure the importance or rank of a journal by calculating the times its articles are cited. The IF can be found on the home page of most online journals.

Peer review is the process used by publishers and editors of academic/scholarly journals to ensure that the articles they publish meet the accepted standards of their discipline. Manuscripts being considered for publication are sent to independent experts in the same field (the author's scholarly or scientific peers). They evaluate the quality of the scholarship, reliability of findings, relevance to the field, appropriateness for the journal, etc.

Plano-Clark and Creswell (2015) provide a very useful tip regarding what sources of literature you should access. They suggest that although you are probably used to searching for books on a particular topic, it is important to "focus on reading recent research studies published as journal articles to learn the most up-to-date information in your profession" (p. 11). As a general rule, articles published within the past 10 years should give you a good idea of what is current in your profession.  
```

### Learning Activity: Watch, Read, and Search for Journal Articles

```{block, type='reflect'}

📺  Watch the following video where Dr. Strong explains why it is important to access scholarly literature (_Note: This video is 31 minutes in length_).

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/8a904ba1-9a21-4663-9f05-3ba1b3520d35?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>



📖  Next, read [chapters 2 and 4 in the Frederikson & Phelps (n.d.)](https://press.rebus.community/literaturereviewsedunursing) text.  These two chapters discuss sources of information, database searches, and searching the library catalog.

📺 Watch the tutorial "[Preparing a research question for a database search](https://vimeo.com/161998287/7661f12293)".

Click on the library link ["How to search for articles.](http://libguides.twu.ca/library_research/articles)" Begin by selecting one of video tutorials in the section on multi-disciplinary databases such as ["Academic Search Ultimate."](https://vimeo.com/160918763/913f61489b) Watch the video tutorial to get an idea of how to search for a topic in a multi-disciplinary database.

📖 Keeping in mind the topic and specific question(s) you identified in Assignment 1, use the Academic Search Ultimate database at the TWU library to locate a good example of a **journal article**. To do this you will need to:

1. Go to the TWU [library home page](https://www.twu.ca/library){target="_blank"}.
2. In the first search window, click the databases tab and then click the articles and databases link which brings you to a different screen.
3. In the Database Guide screen you will need to select "A-B" from the A-Z list of databases at the bottom of this page.
4. The first database that appears on the next screen is "Academic Search Ultimate." Select this database.
5. You will be asked to sign in as a student with your pass ID and password to access the online database.
6. Once you have signed in, then you will be able to type your topic or question in the search window of "Academic Search Ultimate."

**Searching for Books**

1. Go to [TWU library homepage ](http://libguides.twu.ca/library_research/home){target="_blank"} and click "[How to search for books](http://libguides.twu.ca/library_research/books){target="_blank"}".
2. Begin by selecting one of video tutorials in the section "searching for e-books" such as "[searching for e-books in the classic catalogue](https://vimeo.com/164163119/b24ecb42e6){target="_blank"}." Watch the video tutorial to get an idea of how to search for a topic found in an e-book.
3. Keeping in mind the topic and specific question(s) you identified in Assignment 1, use the library catalog to locate a good example of an **e-book.**

✏️ Answer the questions for this learning activity in your reflective learning journal.

- Briefly describe your experiences in the search for a journal and an e-book, what worked well, what did not, what key search terms did you use, what databases did you search?

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```
## Utilizing Scholarly Literature

After you have determined what sources you will be accessing, you need to conduct a search, and then keep track of your literature search strategy and results. The simplest way to do this is to use an online reference manager that will help you collect, organize, cite and share your references according to the referencing style you will be using.  There are several free, online reference managers available such as [Refworks](https://www.refworks.com/refworks2/help/Welcome.htm), [Zotero](https://www.zotero.org/){target="_blank"}, and [EndNote](http://endnote.com/). TWU library has a research guide that describes [how to use EndNote](http://libguides.twu.ca/EndNote/){target="_blank"}. This library guide will help you sign up for an EndNote account and also help you figure out how to use EndNote to download and store your citations in folders and then input citations into Word documents and create reference lists.

After you have retrieved the results from your database searches and organized them in folders in your reference manager, you need to select documents to review. Begin by reviewing the titles and abstracts. For those articles that you deem worthwhile, skim the article itself to determine if it is relevant to your topic. Read the introduction and literature review and examine the reference list.

As you collect relevant literature you can either enter it into a summary chart or just collect the abstracts. There is no single correct way to do this—but you will need to develop some sort of system that works for you. An example of a summary chart is provided below:

|Category |	Description|
|:---|:---|
|Reference 	|Cite full reference in APA (6th edition) format for a reference list.|
|Research Problem |	Describe the research problem and relevant background information. Include page references for both your summaries and direct quotations.|
|Purpose, Research question or Hypothesis |	Describe the purpose, research question and hypothesis. Include page references for summaries and quotations.|
|Data Collection/Procedure |	Describe how the researcher collected data. What participants did they use? What measures did they use? What method was used?|
|Results/Findings |	Describe the results or findings.|

The research process is not always linear. You may have a great research question or research topic in mind, but as you begin your initial database and library searches you may find yourself changing or refining your topic. Sometimes you will not find any information on the topic you have chosen because the topic is so new and no one has done any research on the topic yet. Sometimes you will not find any information on the topic you have chosen because you are not using the right search terms or keywords.

If you are having difficulty finding research articles and books on your topic then try to re-examine the keywords you are using for your search. Look up synonyms for your keywords and try to find the terms that are used in the research literature. Another helpful tip is to look at the reference list of any articles or books that seem closest to your topic. This can help you to see what sources other authors have used and can be a helpful strategy to track down articles and books on your topic.  


### Learning Activity: Read, Watch and Reflect

```{block, type='reflect'}

📖 Begin this learning activity by reading [Chapter 6 of the Fredericksen and Phelps (n.d.) text](https://press.rebus.community/literaturereviewsedunursing/chapter/chapter-6-documenting-sources/){target="_blank"}.

📺 Next, go to the [TWU library homepage](http://libguides.twu.ca/library_research/home)  and click "[How to develop research skills](http://libguides.twu.ca/library_research/skills){target="_blank"}." Begin by watching all of the video tutorials under the section "upgrading your research skills." There are several short videos in this section on Boolean searches, search history, and other search techniques.

✏️ Answer the questions for this learning activity in your reflective learning journal.

- Briefly describe your experiences with upgrading your research skills.
- What did you find worked well, what did not?
- What boolean searches did you use, what inclusion or exclusion criteria did you select?

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```
## Evaluating Scholarly Literature

After you have found several articles and books related to your research topic and skimmed them for relevance, the next step is to evaluate your information sources. Unfortunately, not all information that you will come across is going to be credible and reliable. Just because you find articles and books at the library does not mean that the information will be accurate or of high quality.

As an MA Leadership student, and as a professional, it is imperative that you are able to critically evaluate information you are reading in order to conduct quality research yourself, inform policies and improve your professional practice. To evaluate a source for quality and credibility you need to consider the following:

*   **Authority:** Who is the author? What are the author's credentials (educational background, past writing experience, expertise on the topic)? Is the author's name cited in other sources or reference lists? A simple google search will help you explore these questions.
*   **Currency:** When was the source published? Is the source current or out of date for your topic? Remember the general rule is to use sources that have been published within the past 10 years.
*   **Purpose:** What is the author’s intention? Is the information the author's opinion or is the author communicating evidence-based results? Who is the author's intended audience? Is it the academic community or consumers? Is the author's point of view objective and impartial? Is the language in the article or book free of emotion or bias?
*   **Content:** What kind of information is provided in the article or book? Is it a research article, popular book or opinion piece on a blog? Is the information provided backed up with references or sources? What is the length of the reference list?
*   **Publication type/process:** Who published the source? Was the source peer-reviewed? Is the publisher a university press or a large reputable publisher? Is it from a government agency? Is the source self-published?
*   **Bias and special interests:** According to Panucci and Williams (2010) bias can occur during all phases of research from design, implementation, and analysis to publication. Therefore, careful attention to the interpretation of research results and study design will help identify bias. Driscoll and Brizee (2017) suggest that when it comes to publishing research reports, "most major publishers are out to make a profit and will either not cater to special interest groups or will clearly indicate when they are catering to special interest groups".


### Additional sources for finding scholarly literature: {-}

I also wanted to mention two other sources of information that you can use to gather information on your research topic.  The first is viewing the TED talk videos.  These videos are a great resource to help you become familiar with a researcher and their work on a specific topic.  You can search almost any topic on the TED website, the videos are usually under 20 minutes, and are very good.  You can find TED site here: [https://www.ted.com](https://www.ted.com/){target="_blank"}.

The second resource is using the reference lists at the back of a book or of a journal article on your topic.  These are both great places to find additional sources of information on your topic and also help you become familiar with who is publishing information in your area of interest.  

### Learning Activity: Watch, Read, and Reflect
```{block, type='reflect'}

📺 Begin this learning activity by watching the following video where Dr. Strong explains how to evaluate your sources.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/6c53930b-19a1-4330-9ccd-46fbbf16fd85?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>



📖 Next, read [chapter 6: Evaluating Sources in the Fredericksen and Phelps (n.d.)](https://press.rebus.community/literaturereviewsedunursing/chapter/chapter-5-documenting-sources/) text.

📺 Next, watch the following videos:
- [assessing online resources](https://vimeo.com/162602381/1b0d684fb6) and [evaluating a journal article](https://www.youtube.com/watch?v=z6dOGkpI6H4).

✏️ Answer the questions for this learning activity in your reflective learning journal at the bottom of this page.

- Briefly describe how you found your online sources and whether or not you think they will be helpful resources for your topic.

- What sources of information will you use the most to conduct research on your topic?

- How will you evaluate these sources to make sure they are credible and reliable sources of information?

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```
## Unit 2 Summary {-}

In this unit you have learned about the research process and what is involved in asking good research questions.  You have learned how to identify different scholarly sources, how to access those sources through the TWU library, and how to keep track of your literature search strategies and results.  In addition, you have learned how to critically evaluate scholarly sources.  The activities in this unit are directly related to your third, fourth and final assignments in this course.  Coming up next week in Unit 3 you will be discovering how to develop your professional scholarly voice, particularly through your scholarly writing.  


## Unit 2 Assessment {-}
```{block, type='assessment'}
#### Prepare for your Discussion {-}

In your learning pod/discussion post this week, you will do some research on the benefits of a popular health topic.

Begin by searching for literature on your topic. Choose an article, or blog post, or video, or other internet source that you found on your topic. Determine if your source is credible or not. What did you find out about the credibility of your source?

Next, as a group you will evaluate the source of the information that you discovered by providing information about the following:

* Authority – Who is the author and who published the source?
* Currency – Is the source current or out of date?
* Purpose – What is the author’s intention? Is it stated clearly?
* Publication process – Has the article been peer reviewed? How do you know?
* Bias and special interests – Did the source indicate any conflicts of interest?

---

### Complete Assignment #1: Clarifying Your Research Interest. {-}

In this assignment, you will discuss your leadership interests (personal and/or professional) and generate research questions amenable to scholarly inquiry.

**Please see the instructions for this assignment under the Assignments tab.**

```

## Checking Your Learning {-}
```{block, type='progress'}

Now that you have completed the learning activities and assignments for this unit, check the list below to see if you can do the following:

1. Can you identify a research interest and develop a good research question?
2. Can you employ different search strategies to locate different sources of scholarly literature?
3. Can you evaluate the credibility and reliability of sources of scholarly literature?

_Feel free to review topics more in depth or continue on to the next unit._
```

## References {-}

Booth, W. C., Colomb, G. G. & Williams, J. M. (2008). _The Craft of Research_(3rd ed.) Chicago: The University of Chicago Press, p. 51-65

Creswell, J. (2003). _Research design: Qualitative, quantitative, and mixed methods approaches_ (2nd ed.). Thousand Oaks, CA: Sage.

Driscoll, D. L. & Brizee, A. (2017). _Evaluating print versus internet sources._ Retrieved from [https://owl.english.purdue.edu/owl/resource/553/04/](https://owl.english.purdue.edu/owl/resource/553/04/){target="_blank"}

Fenigstein, A., Scheier, M. F., & Buss, A. H. (1975). Public and private self-consciousness: Assessment and theory. _Journal of Consulting and Clinical Psychology, 43_(4), 522-527.

Hart, E. A., Leary, M. R., & Rejeski, W. J. (1989). The measurement of social physique anxiety. _Journal of Sport and Exercise Psychology, 11_, 94-104.

Leary, M. R. (1983). A brief version of the Fear of Negative Evaluation Scale. _Personality and Social Psychology Bulletin, 9_, 371-376.

Leary, M. R., & Atherton, S. C. (1986). Self-efficacy, social anxiety, and inhibition in interpersonal encounters. _Journal of Social and Clinical Psychology_, _4_(3), 256-267.

Pannucci, C. J. & Wilkins, E. G., (2010). Identifying and avoiding bias in research. _Plastic and Reconstructive Surgery, 126_(2), 619-625.

Plano-Clark, V., & Creswell, J. (2015). _Understanding research: A consumer’s guide_ (2nd ed.). Boston, MA: Pearson.

Schlenker, B. R., & Leary, M. R. (1982). Social anxiety and self-presentation: A conceptualization model. _Psychological Bulletin, 92_(3), 641-669. _The Step-by-Step Guide & Research Rescue: Finding and Narrowing Your Topic_ (2017). Retrieved from [http://guides.lib.byu.edu/c.php?g=216340&p=1428396](http://guides.lib.byu.edu/c.php?g=216340&p=1428396){target="_blank"}
