# Developing Your Professional Voice
### Overview {-}
An essential attribute of scholarly work is that of writing well. Writing well involves several components. Some are conceptual—reasoning and developing a logical argument. Others reflect the mechanics of good written communication—organization of a manuscript, style and language use, grammar, spelling, and punctuation. APA formatting also falls within this category of the mechanics of writing well. The MA Leadership program uses the APA Manual (7th edition) as the model for formatting written work formally submitted. Unit 3 is devoted to helping you become familiar with some of the more common elements of scholarly writing and APA style.  

## Topics {-}

Unit 3 is divided into 4 topics:

1. Developing Your Professional Voice
2. What is Scholarly Writing?
3. How to Write a Scholarly Paper  
4. APA Citations and References



## Learning Outcomes {-}

When you have completed this unit you should be able to:

1.  Describe the importance of scholarly writing for leadership.
2.  Apply the basic rules of APA style which includes the structure and content of a paper, writing clearly and concisely, the mechanics of style, citing sources and formatting references.
3.  Create an APA style paper.

## Activity Checklist {-}

| **Learning Activities** |
|----|
|**Activity:** Watch a video and reflect in your learning journal.   |
|**Activity:** Read chapter 2 of the APA (2019) manual, watch a video, and practice your skills in your learning journal.   |
|**Activity:** Read chapter 4 of the APA (2019) manual, watch a video tutorial, and reflect in your learning journal.   |
|**Activity:** Read chapter 8 of the APA (2019) manual, watch a video, take a quiz, and practice your skills in your learning journal.   |
|**Activity:** Read chapter 9 of the APA (2019) manual, watch a video, and practice your skills in your learning journal.   |
|**Activity:** Read an article and answer questions in your journal.   |
|**Assessment:** Contribute to the course discussions. See Assessment tab in Moodle for details.  |
|**Assessment:**  Complete Assignment #2: Literature Search.   |



## Resources{-}

Here are the resources you will need to complete the unit:

*   American Psychological Association (2019). _Publication manual of the American Psychological Association_ (7th ed.). Washington, DC: American Psychological Association.
*   Onwuegbuzie, A. J., Combs, J. P., Slate, J. R., & Frels, R. K. (2010). Evidence-Based Guidelines for Avoiding the Most Common APA Errors in Journal Article Submissions. _Research in the Schools, 16_(2), ix-xxxvi.
*   Peterson, J. (2017). The Power of Writing [video file]. Retrieved from https://www.youtube.com/watch?v=bfDOoADCfkg  
*   Plano-Clark, V., & Creswell, J. (2015). _Understanding research: A consumer's guide_ (2nd ed.). Boston, MA: Pearson.


## Developing Your Professional Voice

In Unit 3 you will be discovering how to develop your professional scholarly voice, specifically through your scholarly writing.  This means that you will be reading content that will help you understand that there are different writing styles that are used in the world of academia and how important it is to use APA style in the MA Lead program.

Your learning activities this week are focused on applying the APA standards for general aspects of writing, mechanics of writing and citing sources.  You will also have a chance to apply these skills in assignment 3 which is the literature search and assignment 4 which is the scholarly article critique, and then continue to practice them in assignment 5 - the formal literature review. Let's get started!


When you are asked to write a scholarly paper in graduate school, what you are really being asked to do is to develop your professional voice (McDonald, 2011). A professional voice can be described as utilizing formal language, good vocabulary and appropriate tone in your written and oral communication (Walden University Writing Center, 2017). Characteristics of a strong professional voice are writing concisely, with clarity and precision, and appropriately citing your sources (McDonald, 2011).

Developing your professional voice is important because some students will turn their papers into professional manuscripts that will be submitted to a journal or a book. Some students may be asked to present their work at a professional conference. McDonald suggests that "for most students, writing papers in graduate school is an exercise in presenting important information in an easy to understand and concise way" (p.125).

A well developed professional voice can also benefit you in your professional context. For example, at work you may be asked to write a briefing document for your school or hospital board, or you may be asked to share your ideas with other professionals at a conference, or you may be asked to write a grant to fund your organizations new project. These are just three examples of professional situations where it is important to have a well-developed professional voice so that you can communicate in a clear and concise way.

In order to communicate well, you need to have a system to organize your thoughts so that the information you are writing is presented in an organized and clear manner. There are a wide variety of publication styles that are employed today in universities and in scholarly publications. A few that you may be familiar with are Chicago style, MLA style, Turbian style and APA style. The American Psychological Association (APA) has developed a writing style that is used to establish a standard of written communication. This standard includes: the organization of content, writing style or writing mechanics, citing references, and how to prepare a manuscript for publication in certain disciplines (APA, 2010). The MA Leadership program uses the APA Manual (6th edition) as the model for formatting written work formally submitted.

Aside from simplifying the work of your instructors by having everyone use the same format for a given paper, using APA style makes it easier for readers to understand a text by providing a familiar structure they can follow. Abiding by APA's standards as a writer will allow you to:

1.  Provide readers with cues they can use to follow your ideas more efficiently.
2.  Provide readers with dates of publications to help them locate current information that may be of interest to them.
3.  Allow readers to focus more on your ideas by not distracting them with unfamiliar formatting.
4.  Establish your credibility in the field by demonstrating an awareness of your audience and their needs as fellow researchers.


### Learning Activity: Watch and Reflect
```{block, type='reflect'}

📺 In this learning activity you will begin by watching the following video "The Power of Writing" by Dr. Jordan Peterson.  In the video, Dr. Peterson explains the importance of writing.

<iframe width="750" height="433" src="https://www.youtube.com/embed/bfDOoADCfkg" frameborder="0" allowfullscreen></iframe>

✏️ Answer the questions for this learning activity in your reflective learning journal.

- What is your previous experience with APA style?  
- Discuss why you think scholarly writing could be important in your leadership context.  

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```

## What is Scholarly Writing?

According to Heady (2013), graduate-level (or scholarly) writing is "clear, correct and concise, but it adds the elements of originality and discipline specific expertise" (p. 2). Heady suggests that graduate-level writing explores a topic or a research question in an original way, demonstrates extensive research done on the topic, has a strong organizational structure, and is written for a professional audience. The scholarly writer writes in a way that is skillful, engaging and organized well so that the paper moves from point to point allowing the reader to follow in a logical progression. Heady also states that "a good paper has a clear and obvious structure: you can enter it through a clear, well-composed introduction, you move from section to section, and you exit where you know you have been and what you have seen" (p. 73).

#### Critical Thinking {-}

One of the distinguishing features of scholarly writing is the practice of critical thinking. Critical thinking is "that mode of thinking — about any subject, content, or problem — in which the thinker improves the quality of his or her thinking by skillfully analyzing, assessing and reconstructing it" (Foundation for Critical Thinking, 2015). In addition, critical thinking also involves creating new and original information, conclusions and ideas (Heady, 2013). Scholarly writing, should reflect higher levels of learning. According to Bloom's (1956) taxonomy there are six levels of learning: knowledge, comprehension, application, analysis, synthesis and evaluation. When you are writing a scholarly paper, the focus should not be on just identifying, comprehending material and applying it, your writing should also reflect analysis, synthesis and evaluation. What this means is that your writing (and your thinking) should be able to:
*   Break down ideas into parts and see how those parts relate and are organized to demonstrate analysis.
*   Re-arrange ideas into a new whole to demonstrate synthesis.
*   Make judgments based on internal evidence or external criteria to demonstrate evaluation.

#### Structure and Organization {-}

Writing a scholarly paper often follows a very distinct organizational structure and includes: a title page, an introduction, methods and results, a discussion and a list of references. Let's take a closer look at what should be included in each of these sections of a scholarly paper.

**Title Page:** This is the first page of your paper and it should include a title that summarizes the main topic you will be discussing. It should also include your name (the author), and the institution you are affiliated with (Trinity Western University). It is also helpful if you include the date that you are submitting the assignment.

**Abstract:** This the second page of your paper. The purpose of the abstract is for the author to convey the sentiment of the study in a concise yet informative manner. The abstract is used to determine if the reader is interested in the article and wants to retrieve the article for further information. In 250 words, the abstract explicitly states the overall problem and research question, a brief description of the method, a summary of the findings and important conclusions.

**Introduction:** The purpose of an introduction is to inform the reader of the rationale for your research topic. It should provide a brief overview of the "problem" that you are addressing by providing a broad context, any relevant statistics and describing the importance of your topic. The introduction is also the place where you can define any important terms that may be unfamiliar to the reader and ends with establishing what the key purpose for the paper is. The purpose can be stated as your research question.

**Methods:** The methods section outlines specifically what procedures the author chose to do. In a research report this section will include the sampling methods, sample size, measures, research design, and interventions used. The methods section of a research report looks very different than a methods section of a literature review. In a literature review, the methods section will emphasize how you chose the articles and how you evaluated the articles you reviewed. This will include describing any inclusion or exclusion criteria, the databases that were searched, what key search terms were used, how many records were obtained and how many articles were included in the review. You can refer to the APA (2019) manual for a more detailed explanation of the methods section.

**Results:** The results section reports the findings of the data analysis of a research report or the critical analysis of a literature review. Please refer to the APA manual (2019) for extensive detail about the results of different empirical research reports.

**Discussion:** In the discussion section, the authors describe their own interpretations of the results and link these interpretations back to the literature that was reviewed. In this section the author may discuss the strengths and limitations of the literature, draw conclusions, and make recommendations for future research on the topic.

**Reference List:** The reference list provides a precise list of all of the sources you cited within your paper.

An example of an APA style paper can be found [here](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/documents/20200128APA7StudPaper.pdf).

### Learning Activity: Watch, Read and Practice!

```{block, type='reflect'}

📺 To begin this learning activity, watch the following video where Dr. Strong explains what is scholarly writing.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/16fb4f14-9822-44b7-950f-dcf70dbc7231?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>



📖 Next, read chapter 2 of the APA (2019) manual which discusses the structure and content of an APA style manuscript or paper.

📺 Next, watch the following video on formatting a student paper. This video shows you how to set up your title page and other pages in APA style in a word document.

<iframe width="750" height="433" src="https://www.youtube.com/embed/a9hXY1xiZjo" frameborder="0" allowfullscreen></iframe>

💻 Practice your skills by creating a title page and second page in an APA formatted word document.

_Note, these elements will be evaluated in Assignment 2, 3, and 4._
```



## How to Write a Scholarly Paper

To begin writing a scholarly paper you need to have a research topic in mind.  Then you need to do a review of scholarly literature to obtain a good working knowledge of your topic and then critically evaluate and synthesize the literature you have read.  Finally, you need to have an organizational system for presenting what you know about the research topic. The APA (2019) manual provides a clear organizational structure for presenting scholarly information.

When you begin writing, it is important to remember that you are communicating ideas about a topic to a specific audience.  In order to convey your ideas well, you need to write clearly and concisely with set of specific guidelines.  This is important for two reasons: to keep your reader's attention and to make sure your meaning is clear.  If your writing is long-winded, you will either lose the interest of your reader or confuse your reader.  When your writing is more concise and clear, this will motivate your reader to pay attention to what you have to say.

There are also times when you are writing with a specific purpose in mind. For example, to prepare an assignment or a board briefing document.  Writing clearly and concisely helps a writer communicate what needs to be said in an efficient and effective way.  It is also easy to understand and helps the writer connect with the audience.  Here is an excellent resource by the Purdue Owl Writing Center on "[Tips for Writing in North American Colleges](https://owl.purdue.edu/owl/english_as_a_second_language/esl_students/tips_for_writing_in_north_american_colleges/index.html)".  This website is full of helpful resources to help you improve your scholarly writing.

### Learning Activity: Read, Watch and Reflect!

```{block, type='reflect'}

📖 In this learning activity you will begin by reading chapter 4 of the APA (2019) manual which discusses writing style and grammar.

📺 Next, watch the following video where Dr. Strong discusses the key elements of scholarly writing.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/ac2e6c27-96de-4686-974a-586d03816631?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>


✏️ Answer the questions for this learning activity in your reflective learning journal.  

- Make note of the elements of APA style writing that you struggle with and need to improve on for your next assignment.  
- What resources could you use to improve your scholarly writing?

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```

## Citing the Ideas of Others

Within each section of a scholarly paper, each paragraph utilizes a combination three types of content: claims, evidence and transitions. Heady states that "claims are the points you want to prove, interpretations you want to offer, and assertions you want to make, whereas, evidence is the material you use to back up your claims" (pp. 74-75). Some examples of types of evidence that may be used to support claims include: "quotes from a book, citations from an article, data from a study, personal experience, historical facts, statistics, etc. Transitions are one or two words that help you move from one claim to another" (pp. 74-75).

An example of the three types of content (claims, evidence and transitions) included in a paragraph of scholarly writing is provided below from the article "A Systematic Literature Review of Servant Leadership Theory in Organizational Contexts" by Parris and Peachy (2013, pp. 377-378):

> Over the years, some leadership scholars have called attention to the implicit connection between ethics and leadership. A burgeoning new research area and leadership theory that has been linked to ethics, virtues and morality is servant leadership (Graham 1991; Lancot and Irving 2010; Parolini et al. 2009; Russell 2001; Whetstone, 2002). Despite servant leadership being coined by Robert K. Greenleaf over three decades ago in 1970, it remains understudied yet prominently practiced in boardrooms and organizations (Bass and Bass 2008; Spears 2005).

From the example above, you can see that a topic is introduced in the first sentence. A claim with supporting evidence is provided in the second sentence (with references) and the transition begins in the third sentence with the word "despite". The third sentence also includes a claim with supporting evidence (references). This paragraph structure is typical of what you would find in scholarly writing. Scholarly writing involves putting your own thoughts and ideas (claims) in context by ensuring that you are citing the ideas of those who have influenced you (APA, 2010, p.169).

Heady (2013) suggests five general rules you should always follow when you are organizing your paper (p. 80):

1.  You must provide enough background information to give your reader a good working knowledge of your topic.
2.  Your background information must lead logically to your research question.
3.  All claims/ideas/facts must be backed up by evidence.
4.  All evidence must be related to a claim/idea/fact.
5.  If evidence does not back up a claim, you need to explain why and/or account for it.

### Learning Activity: Read, Watch and Practice!
```{block, type='reflect'}

📖 In this learning activity you will begin by reading chapter 8 of the APA manual (7th edition).  

📺 Then, watch the following video where Dr. Strong discusses Academic Dishonesty.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/2e62ae73-8a45-4f79-ba43-7a91a8db8de4?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>



📺 Next, watch the following video tutorial "In-text Citations, Quotations and Plagarism" by Dr. Forlenza.  In the video Dr. Forlenza discusses the importance of properly citing sources in APA format.

<iframe width="750" height="433" src="https://www.youtube.com/embed/8914hv18xnU" frameborder="0" allowfullscreen></iframe>

💻 Next, practice your skills by taking the following [quiz.](http://fgs.athabascau.ca/docs/presentations/APA_Quiz_19Oct11.pdf) Then, you can check your answers to the quiz [here.](http://fgs.athabascau.ca/docs/presentations/APA_QuizAnswers_19Oct11.pdf)

✏️ Then, in your learning journal you can practice citations in APA format for the following:

1. A direct quote less than 40 words with proper in-text citation.  
2. A direct quote more than 40 words with proper in-text citation.  
3. A sentence that refers to an idea from the article (paraphrased), and provide a proper in-text citation.

_Note that these elements will be assessed in assignments 2, 3 and 4._

```


### Reference Lists {-}

The reference list provides a precise list of all of the sources you cited within your paper. APA (7th edition) has many rules to follow for correct formatting of references (see chapters 6 and 7). In general, the APA manual states "when in doubt, provide more information rather than less. Because one purpose of listing references is to enable readers to retrieve and use the sources..." (p.193).

### Learning Activity: Read, Watch and Practice!
```{block, type='reflect'}

📖 In this learning activity, you will begin by reading chapter 9 of the APA manual (7th edition).  

📺 Next, watch the following video tutorial "Reference Lists" by Dr. Forlenza.  In the video Dr. Forlenza discusses the different elements required for, and examples of, references in APA style.

<iframe width="750" height="433" src="https://www.youtube.com/embed/teErxDIPP5M" frameborder="0" allowfullscreen></iframe>

💻 Finally, practice your skills by taking this [online quiz.](http://libraryguides.vu.edu.au/apa-referencing/quiz){target="_blank"}  Then, you can create a reference list in APA format for the following sources:  

1. A journal article  
2. A book or book chapter  
3. A blog post  
4. A doctoral dissertation or master's thesis  
5. An online newspaper or news magazine article  
6. A government report  

_Note that these elements will be assessed in assignments 2, 3 and 4._

```



### Additional APA Resources: {-}

- "The [APA Style Blog](http://blog.apastyle.org/apastyle/){target="_blank"} is the official companion to the Publication Manual of the American Psychological Association, Sixth Edition. It's run by a group of experts who work with APA Style every day. We publish weekly posts to talk about what we love—writing, publishing, and APA Style. We explore what APA Style is and how it works in a variety of areas, including reference citations of every sort, grammar and usage, the publication process, and social media. Occasionally we feature guest bloggers who write about more technical issues." (APA Style Blog, 2017)

- "The [Purdue OWL: Online Writing Lab](https://owl.english.purdue.edu/owl/section/2/10/){target="_blank"} resources will help you learn how to use the American Psychological Association (APA) citation and format style. This section contains resources on in-text citation and the References page, as well as APA sample papers, slide presentations, and the APA classroom poster." (Purdue OWL, 2017)*



### Learning Activity: Read and Reflect!
```{block, type='reflect'}

I just want to encourage you because you have worked through a lot of very technical material in this unit. I want you to know that I expect students to make many APA mistakes in this course. I don’t expect everyone to read the APA manual, watch the tutorial videos, and be able to apply every detail automatically. What I do expect is that you try to begin applying what you have learned about APA every time you write something. You will find with every assignment that you will make APA mistakes, and that is ok. I actually find the best way to learn APA is to make mistakes, correct them, and then learn what to do right the next time. I still make mistakes and I have been working with APA style for many years.

📖 In this learning activity you will begin by reading the following article [Evidence-Based Guidelines for Avoiding the Most Common APA Errors in Journal Article Submissions](https://pdfs.semanticscholar.org/2938/77304aa49a3f75873a35706f746e7431fabc.pdf?_ga=2.80074837.335470918.1560775347-349340290.1554862873){target="_blank"}

✏️ Answer the questions for this learning activity in your reflective learning journal.

- Discuss the elements of APA style or scholarly writing that you struggle with and how you plan to improve on these elements before you submit your next assignment.

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```


## Unit 3 Summary {-}

In this unit, you have learned how important it is to use APA style in graduate level writing.  You have also learned how to apply the APA standards for general aspects of writing and citing sources.


## Unit 3 Assessment {-}
```{block, type='assessment'}
### Prepare for your Discussion

In your learning pod this week/discussion post, you will create a short presentation on a section of the APA manual. You can create a shared presentation using Google Slides or Google Docs. Please be creative!

**The instructions for this group activity are provided under the Assignment tab in Moodle.**

___

### Complete Assignment #2: Literature Search {-}

The purpose of this assignment is to develop your skills to search, retrieve and review relevant literature. This assignment and Assignment 4 will be closely linked. This assignment will include the “paper trail” that provides the details of your search for relevant literature, and Assignment 4 will be the final document that summarizes the findings of your review of precedent literature.

**In order to complete this assignment please go to Assignment 2: Literature Search tab under the assignments tab for more instructions.**

```

### Checking Your Learning {-}

```{block, type='progress'}
Now that you have completed the learning activities and assignments for this unit, check the list below to see if you can do the following:

1. Can you describe the importance of scholarly writing for leadership?
2. Can you apply the basic rules of APA style which includes the structure and content of a paper, writing     clearly and concisely, citing sources and formatting references?
3. Can you confidently create an APA style paper?

_Feel free to review topics more in depth or continue on to the next unit._
```

### References {-}

American Psychological Association (2010). _Publication manual of the American Psychological Association_ (6th ed.). Washington, DC: American Psychological Association.

Critical Appraisal Skills Program (2017). _Appraising the evidence_. Retrieved from [http://www.casp-uk.net/appraising-the-evidence](http://www.casp-uk.net/appraising-the-evidence){target="_blank"}

Foundations of Critical Thinking (2015). _Our conception and definition of critical thinking_. Retrieved from [http://www.criticalthinking.org/pages/our-conception-of-critical-thinking/411](http://www.criticalthinking.org/pages/our-conception-of-critical-thinking/411){target="_blank"}

Heady, E. (2013). _Introduction to graduate writing_ (2nd ed.). Lynchburg, VA: Liberty University Graduate Writing Center.

McDonald, K. E. (2011). Teaching the 6th edition of APA style of writing in counselor education. _Journal of Counselor Preparation and Supervision 3_(2), 124-145.

Parris, D. L., & Peachy, J. W. (2013). A systematic review of servant leadership theory in organizational contexts. _Journal of Business Ethics, 113_(3), 377-395.

Walden University Writing Center (2017). _Basics of scholarly voice._ Retrieved from [http://academicguides.waldenu.edu/writingcenter/scholarlyvoice](http://academicguides.waldenu.edu/writingcenter/scholarlyvoice){target="_blank"}
