# Understanding Qualitative Research Reports

## Overview {-}
In unit 6 we continue our overview of the most common research methods used in leadership research. Remember that the purpose of these overviews is that you will be a more informed consumer of research and a practitioner of evidence-based leadership practices. Specifically, this unit will focus on the research design, method, and analysis and findings of qualitative research reports.  

## Topics {-}

Unit 6 is divided into 3 topics:

1. Qualitative Research Design
2. Qualitative Data Collection
3. Qualitative Data Analysis and Findings



## Learning Outcomes{-}

When you have completed this unit you should be able to:

1.  Evaluate the quality of the methods and findings section of a qualitative research report on servant leadership.
2.  Reflect on the importance of understanding the methods and findings section of a qualitative research report.
3.  Apply what you have learned about qualitative research methods to your own leadership context.

## Activity Checklist {-}

| **Learning Activities** |
|----|
|**Activity:** Read Chapter 9 in your text. Evaluate the research design in the servant leadership article you chose.   |
|**Activity:** Read chapter 10 in your text. Evaluate the participants and data collection in the servant leadership article you chose.   |
|**Activity:** Read chapter 11 in your text. Evaluate the data analysis and findings in the servant leadership article you chose.   |
|**Assessment:** Contribute to the course discussions. See Assessment tab in Moodle for details.  |
|**Assessment:**  Complete Article Critique Part 3 (Assignment #3)   |


### Resources {-}

Here are the resources you will need to complete the unit:

- Plano-Clark, V., & Creswell, J. (2015). _Understanding research: A consumer’s guide_ (2nd ed.). Boston, MA: Pearson.

- *E-Resources:* The articles in this unit can be found through the [TWU library](https://www.twu.ca/library){target="_blank"}.


## Qualitative Research Design
This week in Unit 6 you will be exploring a different approach to research: _**qualitative research methods**_. Plano-Clark and Creswell (2015) define qualitative research as "a set of procedures for collecting, analyzing, and reporting text and image data to answer research questions by exploring participants’ views" (p. 286).

Qualitative research has three distinct purposes:  _**to describe, to explore, and to build theory**_.   Quantitative research and qualitative research designs differ significantly in what data are collected, how data are collected, how data are analyzed and how findings are reported.

As someone who was trained as a quantitative researcher, I would sometimes hear people in my discipline discredit the qualitative approach to research. However, as qualitative research has become more mainstream over the last 20 years, now I would say the most widely held opinion is that there is no best method. “It all depends on what you are studying and what you want to find out” (Bogdan & Biklen, 2007, p. 43). I can certainly appreciate understanding a problem or a phenomenon from both a quantitative and qualitative perspective.  For example, in order to understand the complexity and “messiness” of real-life organizations, it is important for leaders to not just rely only on statistics, but to also examine what employees, consumers, and leaders have to say from a qualitative perspective.

It is really important that you read through the textbook chapters on quantitative (chapters 6, 7, 8) and qualitative research (9, 10, 11) so that you can understand the distinct differences in the two approaches to research.

Qualitative research has been “mainstreamed” in recent years, although in certain disciplines its use is not as widespread. In order to understand the complexity and “messiness” of real-life organizations, leadership investigation is turning increasingly to qualitative research.

Qualitative research designs typically are less structured than in quantitative designs, and are far more flexible. In contrast to quantitative research design’s resting solidly on theoretical frameworks, in qualitative research design the use of theoretical frameworks is not nearly so clear. While some qualitative researchers do employ theoretical frameworks, at least to some degree, others, such as Corbin and Strauss “prefer not to begin our research with a predefined theoretical framework or set of concepts” (Corbin & Strauss, 2008, p. 39). Consequently, qualitative research design has been characterized as an “evolving, flexible, general hunch as to how you might proceed” (Bogdan & Biklen, 2007, p. 45). Theoretical frameworks are employed in qualitative research design to suggest alternate explanations, to help the researcher determine appropriate methodology, and to provide the basis for building and extending theory. The primary consideration for the qualitative researcher is that they remain “open” to new ideas and concepts that might not fit the concepts of the adopted theoretical framework (Corbin & Strauss, 2008, p. 40). Part Four of your reading of the course text (Plano-Clark and Creswell, 2015) focuses on four qualitative methods: narrative, grounded theory, case study, and ethnographic research designs.

### Learning Activity: Watch, Read, and Reflect
```{block, type='reflect'}

📺 Begin this learning activity by watching the following video where Dr. Strong explains Qualitative Research Designs.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/b2c0f818-bd42-4a51-bc83-b348a7fce06d?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

📖 Next, read chapter 9, "Qualitative Research Designs," in Plano-Clark and Creswell (2015).

📖 Then, read the article by Ragnarsson, Kristjánsdóttir, & Gunnarsdóttir (2018). [To Be Accountable While Showing Care: The Lived Experience of People in a Servant Leadership Organization](https://doi.org/10.1177/2158244018801097){target="_blank"} prepare yourself for the group activity in this unit.  

✏️ After reading the article, reflect on the following questions in your learning journal:

- What did you learn from this article that you did not already know about servant leadership?
- What are the potential challenges for studying servant leadership using a qualitative research approach?
- Make some notes about what you would look for in a high quality "Qualitative Research Design".

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```
## Qualitative Data Collection

Qualitative research data collection is typically based on one or more of the following methods: observation (including participant observation), open-ended interviewing, first person accounts, and the review of various documents. Data collected is descriptive, and may consist of personal documents, field notes, various records of people’s own words (including video and voice recordings and written transcripts), photographs, official documents, and other artifacts. Data is collected from small, non-representative samples selected through various sampling strategies including theoretical, purposeful, and snow ball sampling (Bogdan & Biklen, 2007, p. 45).

A dominant word encountered in qualitative research is triangulation. Triangulation is a term borrowed from navigation and surveying, and conveys the notion that multiple sources of information will help establish a fact (Bogdan & Biklen, 2007, p. 115). Multiple sources of data are seen to lead to a fuller, more complete, and more defensible understanding of the phenomena observed. Consequently, multiple methods of data collection are frequently employed within the same qualitative research study. These commonly consist of the researcher’s field notes, interviews, researcher observations, and analysis of various documents.

In qualitative research, data is usually collected until saturation is achieved. Saturation is a term employed that simply means that no new information relevant to the development of categories, properties, dimensions and variances is forthcoming from continued data gathering (Corbin & Strauss, 2008, p. 143). In effect, findings begin to replicate, and not add anything substantially new (Gall, Gall & Borg, 2007, p. 278). Qualitative researchers oft

### Learning Activity: Read, Evaluate and Reflect
```{block, type='reflect'}

📺 Begin this learning activity by watching the following video, where Dr. Strong explains "Qualitative Data Collection".

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/049676fa-bcb7-42ad-89ce-9318d20f02f3?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

📖 Next, read chapter 10, "Participants and Data Collection," in Plano-Clark and Creswell (2015).

✏️ Practice evaluating the participants and data collection of the Ragnarsoson et al., article. Use the quality criteria discussed in Table 10.3 (Plano-Clark & Creswell, 2015) to evaluate the quality of the participants and data collection.

✏️ Finally, in your learning journal, identify what your overall quality rating is of this section and list three pieces of evidence to support your rating. Make some notes about what you would look for in a high quality qualitative research report.

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```
## Qualitative Data Analysis and Findings

Qualitative research data analysis typically employs analytic induction, is ongoing throughout the research, and seeks to identify themes and concepts emergent in the data (Bogdan & Biklen, 2007, p. 46). This is a dynamic process in which the researcher breaks data apart into its various components in order to identify their properties and dimensions (Corbin & Strauss, 2008, p. 46). Because data might suggest more than one story, analysis is an interpretive act that often begins, as in Glaser and Strauss’ constant comparison, from the very onset of data collection (Gall, Gall & Borg, 2007, p. 469).

Data analysis involves “working with the data, organizing them, breaking them into manageable units, coding them, synthesizing them, and searching for patterns” (Bogdan & Biklen, 2007, p. 159). Analysis involves data interpretation where ideas about the findings are related to broader concerns and concepts. Levels of analysis can range from the superficial description to theoretical interpretation (Corbin & Strauss, 2008, p. 80). The task is monumental. Software such as HyperRESEARCH© is of great assistance in helping the researcher assign codes to text data, which assists in the identification of concepts and themes. Qualitative research findings or results are usually presented in a narrative form. This can take many forms, and be organized in a variety of ways including the use of tables and figures when appropriate. Chapter 11 of the course text provides a concise discussion of this topic.

Because qualitative research can involve the investigation of as few as one research participant (as in a case study), great caution is exercised in making sweeping generalizations. In fact, because the term generalizability itself is strongly associated with quantitative research with much larger samples, Gall, Gall and Borg suggest the term applicability is more appropriate to the different processes and types of evidence associated with qualitative research (2008, p. 477).

### Learning Activity: Watch, Read, and Reflect
```{block, type='reflect'}

📺 Begin this learning activity, by watching the following video where Dr. Strong explains "Qualitative Data Analysis".

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/6386b293-dc9f-4081-b553-47909c21c916?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>



📖 Next, read chapter 11, "Data Analysis and Findings," in Plano-Clark and Creswell (2015).

✏️Practice evaluating the data analysis and findings of the Ragnarsoson et al., article. Use the quality criteria discussed in Table 11.3 (Plano-Clark & Creswell, 2015) to evaluate the quality of the data analysis and findings.

✏️ Finally, in your learning journal, identify what your overall quality rating is of this section and list three pieces of evidence to support your rating. Make some notes about what you would look for in the results section of a high quality qualitative research report.

*Note that your journal is not graded, but will help you in your assessment for this unit.*
```
## Unit 6 Summary{-}

In this unit you have learned that qualitative research has three distinct purposes:  _**to describe, to explore, and to build theory**_.  Qualitative research designs typically are less structured than in quantitative designs, and are far more flexible. The data are usually collected from a few cases or individuals so findings cannot be generalized to a larger population, but issues can be examined in great detail. Findings can however be transferable to another setting.  


## Unit 6 Assessment{-}
```{block, type='assessment'}
#### Prepare for your Discussion
In your learning pod/discussion post this week, you will read the **Methods and Findings** section of **one** of the ***qualitative*** SL articles.  While you read the methods and findings sections, you will evaluate these sections using the criteria provided in the Plano-Clark and Creswell text for the research design, participants and data collection, and findings.  

**_You will prepare a short summary of your evaluation and post it on the Unit 6 forum. Remember to provide the title of your article in your summary._**


```

### Checking Your Learning{-}
```{block, type='progress'}
Now that you have completed the learning activities and assignments for this unit, check the list below to see if you can do the following:

1. Can you evaluate the quality of the methods and findings section of a qualitative research report on servant leadership?
2. Can you discuss the importance of understanding the methods and findings section of a qualitative research report?
3. Can you apply what you have learned about qualitative research to your own leadership context?

_Feel free to review topics more in depth or continue on to the next unit._
```

### References{-}

Anderson, C. (2010). Presenting and evaluating qualitative research. _American Journal of Pharmaceutical Education ,74_ (8), 1-17.  Retrieved from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987281/pdf/ajpe141.pdf

Bogdan, R., & Biklen, S. (2007). _Qualitative research for education: An introduction to theories and method_ (5th ed.). Boston, MA: Pearson.

Corbin, J., & Strauss, A. (2008). _Basics of qualitative research_ (3rd ed.). Los Angeles, CA: Sage.

Gall, M., Gall, J., & Borg, W. (2007). _Educational research_. Boston, MA: Pearson.

Leedy, P. D., & Ormrod, J. E. (2010). _Practical research: Planning and design_. Upper Saddle River, NJ: Merrill.

Plano-Clark, V., & Creswell, J. (2015). _Understanding research: A consumer’s guide_ (2nd ed.). Boston, MA: Pearson.
