# Action Research: Studies that Solve Practical Problems

## Overview {-}
We want to shift our focus from the highly theoretical and rigidly structured forms of formal research that we have considered thus far and look at a form of research that you are more likely to employ as a leader—action research. Action research has evolved as a method well suited to leadership and organizational studies as well as in educational settings. In unit 8 we will explore how action research is related to, and yet distinct from, other forms of research that we have explored to date. If formal research approaches (qualitative, quantitative and mixed methods) are aimed at generating new knowledge, action research is aimed at finding solutions to local problems and issues.  

## Topics{-}

Unit 8 is divided into 3 topics:

1. What is Action Research?
2. The Action Research Method
3. Evaluating An Action Research Study



## Learning Outcomes{-}

When you have completed this unit you should be able to:

1. Identify a practical problem that can be addressed with action research.

2. Design an action research project that might be utilized in your leadership practice.

3. Evaluate an action research project proposal.


## Activity Checklist {-}

| **Learning Activities** |
|----|
|**Activity:** Read chapter 13 of your Plano-Clark & Creswell (2015) text.Watch a video and choose a problem for your action research project.   |
|**Activity:** Create a podcast or video to explain your idea for an action research project.   |
|**Activity:** Peer review one action research project posted by colleague's in the class.   |
|**Assessment:** Contribute to the course discussions. See Assessment tab in Moodle for details.  |
|**Assessment:**  Complete Assignment 4: Scholarly Article Review   |



## Resources{-}

Here are the resources you will need to complete the unit:

- Plano-Clark, V., & Creswell, J. (2015). _Understanding research: A consumer's guide_ (2nd ed.). Boston, MA: Pearson.

- Spencer, J. (2017, January 12). _What is action research?_ (Video file). Retrieved from [http://www.spencerauthor.com/how-action-research-sparks-innovation-and-boosts-creativity-in-the-classroom/](http://www.spencerauthor.com/how-action-research-sparks-innovation-and-boosts-creativity-in-the-classroom/){target="_blank"}

## What is Action Research?
This week in Unit 8 you will get a chance to explore a new approach to research.  Action research "is a disciplined process of inquiry conducted _by_ and _for_ those taking the action" (Sagor, 2000, para. 1). Its purpose is to solve local/practical problems through the application of systematic investigation.  The problem is local, the investigation is local, and there is little concern for generalizing results to other settings. Action research may employ virtually any research methodology, and will commonly be conducted collaboratively with other professionals.  Action research differs from more formal research in some important ways that you will uncover in the readings this week.

Action research has been defined as “a form of applied research whose primary purpose is to increase the quality, impact, and justice” of professional practice (Gall, Gall & Borg, 2007, p. 597). Its purpose is to solve local problems through the application of systematic investigation. The problem is local, the investigation is local, and there is little concern for generalizing results to other settings. Gay (1987) states “the primary goal of action research is the solution of a given problem, not contribution to science” (p. 8). Action research may employ virtually any research methodology, and will commonly be conducted collaboratively with other professionals. Action research differs from more formal research in some important ways.

Formal research is typically conducted by researchers with a great deal of experience and/or training in research, and who wish to produce new, generalizable knowledge. Action research is typically conducted by those with much less experience in and knowledge of research, with the intention of solving a current, local problem. Formal research typically employs random or representative sampling techniques, while action research will typically employ convenience sampling. Formal research designs typically exhibit rigorous controls, with a long time frame, while action research designs display more casual procedures, often employing emergent designs, and are focused on short-term time frames (Gall, Gall & Borg 2007, p. 598). Action research can serve personal, professional, and political purposes.

At its heart, action research is cyclical in nature. Gill and Johnson (2002) assert that action research is a planned intervention by a researcher, or more often a consultant, into some natural social setting, such as an organization. The effects of that intervention are then monitored and evaluated with the aim of discerning whether or not that action has produced the expected consequences. In other words, the researcher acts upon his or her beliefs or theories in order to change the organization (Gill & Johnson, 2002, p. 71). Going back to Boyer’s model of scholarship, what distinguishes action research as research or scholarly inquiry (i.e., as more than problem-solving) is the explicit commitment to contribute to existing knowledge, even if it is not widely generalizable.

According to Mutimbi and Khaila (2011):

> A standard research methods course at university emphasizes scientific ways of conducting research. Students are taught scientific methods of collecting data, analyzing it and reporting. They collect data and analyse it in ways that enable them to describe situations as they exist, and they come up with long ‘wish lists’ in the form of recommendations for others to implement. They become experts in analyzing and developing models to describe situations – _but they cannot change the situations_. In other words, they are taught to describe problems, but not to solve them. These methods are not suitable for workers who are grappling with real life issues and are looking for ways of helping solve their problems. They need research approaches and methods that enable them to generate data that they can use to solve problems. (p. 27)

### Learning Activity: Watch, Read and Reflect
```{block, type='reflect'}

📺 Begin this learning activity by watching the following video where Dr. Strong explains what action research is.

 <iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/bf37d72e-1b01-4a98-9c9b-85f4d48e0f88?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>



📖 Next, read chapter 13, "Action Research Designs," in Plano-Clark and Creswell (2015).

📖 You can review the following research articles to give you an idea of different action research projects - but these articles are **not** required readings. The articles can be found through the [TWU library](https://www.twu.ca/library){target="_blank"}.

+ Bhatnagar, V. (2017). Systemic Development of Leadership: Action Research in an Indian Manufacturing Organization. *Systemic Practice & Action Research*, *30*(4), 339–376.

+ Tucker, C. M., Williams, J. L., Roncoroni, J., & Heesacker, M. (2017). A socially just leadership approach to community-partnered research for reducing health disparities. *The Counseling Psychologist*, *45*(6), 781–809.

+ Cardiff, S., McCormack, B., & McCance, T. (n.d.). Person-centred leadership: A relational approach to leadership derived through action research. *Journal of Clinical Nursing*, *27*(15–16), 3056–3069.

+ Wessels, E., & Wood, L. (2019). Fostering Teachers’ Experiences of Well-Being: A Participatory Action Learning and Action Research Approach. *South African Journal of Education*, *39*(1).

✏️ In your reflective learning journal, answer the following questions:

- What are some of the strengths and challenges of using an action research approach?
- What would you would look for in a high quality action research report?

_Note that your journal is not graded. These questions relate to the assessment questions for this unit._
```
## The Action Research Method

The method of action research presented by Gill and Johnson (2002) draws on Lewin’s theory of studying things through changing them (i.e., change as the method or process of research). Stringer and Genat (2004) outline a research process that has action as final step, after eliciting stakeholder perspectives, analyzing data (identifying key features of stakeholder experience), and writing the research report (i.e., change as the outcome of research). Stringer and Genat also emphasize the participatory process of action research in which change is brought about through the participants in the research project, rather than being imposed on them from the outside. They explain that a major purpose of participatory approaches to inquiry is to bring people together in a dialogic and productive relationship, enabling the development of a sense of community through the sharing of perspectives, the negotiation of meaning, and the development of collaboratively produced activities, programs, and projects (Stringer & Genat, 2004, p. 9).

Glanz (1998) has suggested that an action research cycle consists of six steps, which may or may not be always addressed in order. The usual first step is to select a focus. This is typically followed by data collection, then the analysis and interpretation of the data. The analysis and interpretation of data typically would suggest action to be taken. Action is followed by a period of reflection on the results of the action, and on the basis of this reflection, the action is either continued or modified. The cycle then comes full circle to begin with a new focus (p. 27).

### Learning Activity: Watch and Create
```{block, type='reflect'}

📺  To begin this learning activity, watch the following video where Dr. Strong explains how to create an action research project.

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/f0d4390e-fbf9-464e-a5dc-94d745038509?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

🤔 Next, think about some practical problems that you have faced in your professional life that you would like to change.

✏️ In your reflective learning journal, list three problems that matter to you and that you think you can systematically address in your work situation. After reflecting on these problems, select one that you would like to address for your action research project.

>  *Note: The following learning activity will be created in groups during class time.  For asynchronous learners, your action research presentation may be completed individually.*

📺 In this learning activity, you will create an idea for an action research project based on one of the practical problems you have identified from your professional life. You will present this project idea in a podcast or video for your colleagues.

This learning activity is intended to be informal, so do not spend too much time planning and researching your topic. Please note that if you are sharing confidential information from your place of employment that you should change the name of your employer or any people involved.

##### Instructions:{-}

1. Using one of the practical problems you identified above, create an idea for an action research project following the steps described by Plano-Clark and Creswell (2015) on pp. 440-442.

2. Put a presentation together and record your presentation so that it can be presented to your colleagues for feedback.

3. Your introduction should include your key problem and explain the structure of your presentation.

4. Your project idea should relate to a practical leadership issue you are currently facing.

5. Your project idea should be clear and well organized.

6. Your project should fit within 3-5 minutes but no more than 6 minutes (8 slides maximum).

7. Provide a conclusion that gives a call to action.

8. Upload your presentation to another suitable online platform and post a link to your presentation on the Unit 8 discussion forum.



**Reminder:** Make sure you take some time to practice what you are going to say (I highly recommend creating a script) and give yourself lots of time to record, make mistakes, re-record, make more mistakes, take a break, re-record and then post it on the discussion forum.

_Note this learning activity is ungraded._
```
## Evaluating An Action Research Study

According to Plano-Clark and Creswell (2015):

> Action research has gained support across many disciplines including education, nursing, and clinical work. [However], some view it as an “informal” process of research, conducted by practitioners who are not formal academic researchers.  Action researchers typically report results of their studies in informal venues, such as conferences, websites, or local groups in the community. Hence, the design may not have the rigor and systematic approach found in other designs. However, it is precisely this flexibility and responsiveness that makes action research studies among the best source of information to learn about potential solutions to real problems because they are conducted in real professional settings by real practitioners. Therefore, when evaluating an action research study, you need to keep in mind the intent and standards for this particular form of research. (pp.443-444)

### Learning Activity: Peer-review an Action Research Project
```{block, type='reflect'}

Next, you will peer review one Action Research project by colleagues in the class. Note: You will not be able to do this until everyone has posted their presentations in the Unit 8 forum.

I have posted the peer-review partnerships in Moodle under the assignments tab. This means that you will be assigned to peer-review one of your colleagues presentations. For your peer-review make notes about the strengths of the project idea as well as areas to work on (clarify, more analysis, more personal application) by using the evaluation criteria for an action research study outlined by Plano-Clark and Creswell.

Here are the questions you should address in your evaluation:

1. Does the project focus on a real problem in practice?
2. Does the researcher plan to study his or her own practices or plan to collaborate with community members?
3. Does the project include careful reflection about the problem?
4. Does the researcher plan to gather several sources of information (e.g., qualitative and quantitative procedures)?
5. Does the researcher develop a clear plan for addressing the problem?
6. Does the project include reflecting, thinking, looking, and gathering information and acting?
7. Will the results of the project enhance the lives of those involved?

✏️ Summarize your notes in a response to your colleagues project and please post your review in the Unit 8 Discussion Forum as a reply on their post. Remember that your response will be visible to all members of the class.  

_Note. This activity is ungraded, but gives you an opportunity to provide formative feedback for your colleagues._
```
## Unit 8 Summary{-}

In this unit you have discovered how action research is related to, and yet distinct from, other forms of research that we have explored to date. You have developed your own action research project to find a solution to your own practical problems.  You have also developed a strong sense of what a good quality action research project is.  


## Unit 8 Assessment {-}
```{block, type='assessment'}
### Prepare your Presentation

In your learning pod/discussion post this week, you will spend most of your time preparing an action research project presentation. Make sure you all have time to share your project idea. This will be a brainstorming session so that you can get peer feedback on your project plan before you submit it.

**Here are the instructions for developing your action research plan:**

Think about some practical problems that you have faced in your professional life that you would like to change. Share one problem with your group that you would like to address for your action research project. Discuss why it is a problem and discuss why this problem is important to you. Next, you will create an idea for action research project following the steps outlined by Plano-Clark and Creswell (2015, pp. 440-442) below.  Discuss the following steps with your group to provide each other with peer-feedback:

1. Determine if an action research project is feasible. Remember, you want to use action research when you want to systematically address a practical problem in your work situation or community, and to advance your own professional development.
2. Specify the problem you want to study. Identify the question you want to answer. The most important factor in action research is that you need to solve a practical problem. This problem is one that you face in your own practice or in your community.
3. Identify the information that you need. This means that you need to decide who your participants will be, how many people you will study, how you will access these participants.  Be specific.
4. Describe how you will collect data.  Your choices are to collect quantitative data (e.g., attendance data, test scores, or a short survey) or qualitative data (e.g., reflection journals or in-person interviews, focus groups) or both.
5. How will you analyze the data that you collect?  Will you use quantitative, numerical data that will be examined using descriptive analyses or qualitative, text-based data using content analyses exploring general themes.
6. In action research, it is not enough to produce results from your data, you need to use  those results to develop a plan for action. Describe how the results of this project will help enhance the lives of those involved.

7. Finally, describe how you are going to implement your plan. You also need to reflect on what you have learned from implementing your plan and discuss how you will share your results with others.

-----

### Complete Assignment #4: Scholarly Article Review

This assignment is the next step in moving toward a literature review paper. Remember, your eventual task is to create a literature review that is synthesized from the individual research articles you have read and have taken notes on in Assignment 2. Part of that process involves the need to be able to look back at your notes and quickly see what you actually noted from these articles.  For this assignment you will write a review of a journal article using the guidelines provided under the Assignment 4: Scholarly Article Review tab under the Assignments tab.  

```

-----

### Checking Your Learning {-}
```{block, type='progress'}
Now that you have completed the learning activities and assignments for this unit, check the list below to see if you can do the following:

1. Can you identify a practical problem that can be addressed with action research?
2. Can you design an action research project that might be utilized in your leadership practice?
3. Can you evaluate an action research project proposal?

_Feel free to review topics more in depth or continue on to the next unit._
```


### References {-}

Gall, M., Gall, J., & Borg, W. (2007). _Educational research: An introduction (8th ed.)._ Boston, MA: Pearson.

Gay, L. (1987). _Educational research: Competencies for analysis and application._ Columbus, OH: Merrill.

Gill, J., & Johnson, P. (2002). _Research methods for managers_ (3rd ed.). Thousand Oaks, CA: Sage.

Glanz, J. (1998). _Action research: An educational leaders guide to school improvement._ Norwood, MA:

Christopher-Gordon. Leedy, P., & Ormrod, J. (2010). _Practical research: Planning and design_ (9th ed.). Upper Saddle River, NJ: Prentice-Hall.

Mutimba, J. K., & Khaila, S.. (2011). Action research: A practical step-by-step guide for agricultural extension professionals. _South African Journal of Agricultural Extension _, _39_(1), 26-34. Retrieved February 20, 2018, from http://www.scielo.org.za/scielo.php?script=sci\_arttext&pid=S0301-603X2011000100003&lng=en&tlng=en.

Plano-Clark, V., & Creswell, J. (2015). _Understanding research: A consumer's guide_ (2nd ed.). Boston, MA: Pearson.

Sagor, R. (2000). _What is action research?_ In guiding school improvement with action research. Alexandria, VA: ACSD. Retrieved from http://www.ascd.org/publications/books/100047/chapters/What-Is-Action-Research%C2%A2.aspx

Smith, M. K. (2007). _Action research._ Retrieved from [http://infed.org/mobi/action-research/](http://infed.org/mobi/action-research/){target="_blank"}

Stringer, E., & Genat, W. (2004). _Action research in health._ Upper Saddle River, NJ: Pearson Merrill Prentice-Hall.
