# References {.unnumbered}

## u1 {.unnumbered}

Boyer, E. (1997). *Scholarship reconsidered: Priorities for the professoriate.* San Francisco, CA: Jossey-Bass.

Bosher, R. (2009). Why is the scholarship of teaching and learning such a hard sell? *Higher Education Research and Development, 28*(1), 1-15.

Covey, S. (2004). *The seven habits of highly effective people: Powerful lessons in personal change*. New York, NY: Free Press.

Geisler, N., & Watkins, W. D. (2003). *Worlds apart: A handbook on world views* (2nd ed.). Eugene, OR: Wipf and Stock.

Gill, J., & Johnson, P. (2002). *Research methods for managers* (3rd ed.). Thousand Oaks, CA: Sage.

Greenleaf, R. K. (1977). *Servant leadership: A journey into the nature of legitimate power and greatness*. New York, NY: Paulist Press.

Jit, R., Sharma, C. S., & Kawatra, M. (2016). Servant leadership and conflict resolution: a qualitative study. *International Journal of Conflict Management, 27*(4), 591-612.

Jacobsen, D., & Jacobsen, R. (2004). *Scholarship and Christian faith: Enlarging the conversation*. Oxford, UK: Oxford University Press.

Leedy, P., & Ormrod, J. (2010). *Practical research: Planning and design* (9th ed.). Boston, MA: Pearson.

Patton, M. (2001). *Qualitative research and evaluation methods.* Thousand Oaks, CA: Sage. Penner, D. (2017). *INQUIRY 1SS3: Inquiry in the social sciences (Syllabus).* Hamilton, ON: McMaster University. Retrieved from [https://socialsciences.mcmaster.ca/courses/inquiry-in-the-social-sciences/david-penner-c08-winter-2017](https://socialsciences.mcmaster.ca/courses/inquiry-in-the-social-sciences/david-penner-c08-winter-2017){target="_blank"}

Plano-Clark, V., & Creswell, J. (2015). *Understanding research: A consumer's guide* (2nd ed.). Boston, MA: Pearson. Sire, J. (2014, February 14). Eight questions every worldview must answer. Retrieved from [https://www.christianity.com/theology/other-religions-beliefs/8-questions-every-worldview-must-answer.html](https://www.christianity.com/theology/other-religions-beliefs/8-questions-every-worldview-must-answer.html){target="_blank"}

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

Spears, L. C. (1995). *Reflections on leadership: How Robert K. Greenleaf's theory of servant leadership influenced today's top management thinkers.* New York, NY: John Wiley. Zigarelli, M. (2003). Worldview at work: Understanding how your co-workers think, what persuades them, and what does not. Retrieved from [http://www.christianity9to5.org/worldview-at-work/](http://www.christianity9to5.org/worldview-at-work/){target="_blank"}


## u2 {.unnumbered}

Booth, W. C., Colomb, G. G. & Williams, J. M. (2008). *The Craft of Research*(3rd ed.) Chicago: The University of Chicago Press, p. 51-65

Creswell, J. (2003). *Research design: Qualitative, quantitative, and mixed methods approaches* (2nd ed.). Thousand Oaks, CA: Sage.

Driscoll, D. L. & Brizee, A. (2017). *Evaluating print versus internet sources.* Retrieved from [https://owl.english.purdue.edu/owl/resource/553/04/](https://owl.english.purdue.edu/owl/resource/553/04/){target="_blank"}

Fenigstein, A., Scheier, M. F., & Buss, A. H. (1975). Public and private self-consciousness: Assessment and theory. *Journal of Consulting and Clinical Psychology, 43*(4), 522-527.

Hart, E. A., Leary, M. R., & Rejeski, W. J. (1989). The measurement of social physique anxiety. *Journal of Sport and Exercise Psychology, 11*, 94-104.

Leary, M. R. (1983). A brief version of the Fear of Negative Evaluation Scale. *Personality and Social Psychology Bulletin, 9*, 371-376.

Leary, M. R., & Atherton, S. C. (1986). Self-efficacy, social anxiety, and inhibition in interpersonal encounters. *Journal of Social and Clinical Psychology*, *4*(3), 256-267.

Pannucci, C. J. & Wilkins, E. G., (2010). Identifying and avoiding bias in research. *Plastic and Reconstructive Surgery, 126*(2), 619-625.

Plano-Clark, V., & Creswell, J. (2015). *Understanding research: A consumer's guide* (2nd ed.). Boston, MA: Pearson.

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

Schlenker, B. R., & Leary, M. R. (1982). Social anxiety and self-presentation: A conceptualization model. *Psychological Bulletin, 92*(3), 641-669. *The Step-by-Step Guide & Research Rescue: Finding and Narrowing Your Topic* (2017). Retrieved from [http://guides.lib.byu.edu/c.php?g=216340&p=1428396](http://guides.lib.byu.edu/c.php?g=216340&p=1428396){target="_blank"}

## u3 {.unnumbered}

American Psychological Association (2010). *Publication manual of the American Psychological Association* (6th ed.). Washington, DC: American Psychological Association.

Critical Appraisal Skills Program (2017). *Appraising the evidence*. Retrieved from [http://www.casp-uk.net/appraising-the-evidence](http://www.casp-uk.net/appraising-the-evidence){target="_blank"}

Foundations of Critical Thinking (2015). *Our conception and definition of critical thinking*. Retrieved from [http://www.criticalthinking.org/pages/our-conception-of-critical-thinking/411](http://www.criticalthinking.org/pages/our-conception-of-critical-thinking/411){target="_blank"}

Heady, E. (2013). *Introduction to graduate writing* (2nd ed.). Lynchburg, VA: Liberty University Graduate Writing Center.

McDonald, K. E. (2011). Teaching the 6th edition of APA style of writing in counselor education. *Journal of Counselor Preparation and Supervision 3*(2), 124-145.

Parris, D. L., & Peachy, J. W. (2013). A systematic review of servant leadership theory in organizational contexts. *Journal of Business Ethics, 113*(3), 377-395.

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

Walden University Writing Center (2017). *Basics of scholarly voice.* Retrieved from [http://academicguides.waldenu.edu/writingcenter/scholarlyvoice](http://academicguides.waldenu.edu/writingcenter/scholarlyvoice){target="_blank"}

## u4 {.unnumbered}

Bordens, K., & Abbott, B. (2005). *Research design and methods: A process approach* (6th ed.). Boston, MA: McGraw-Hill.

Gall, M., Gall, J., & Borg, W. (2007). *Educational research*. Boston, MA: Pearson.

Greenleaf, R. K. (1970). The servant as leader. *Indianapolis, IN*.

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

## u5 {.unnumbered}

Bogdan, R., & Biklen, S. (2007). *Qualitative research for education: An introduction to theories and method* (5th ed.). Boston, MA:

Pearson. Corbin, J., & Strauss, A. (2008). *Basics of qualitative research* (3rd ed.). Los Angeles, CA: Sage.

Gall, M., Gall, J., & Borg, W. (2007). *Educational research*. Boston, MA: Pearson.

Gill, J., & Johnson, P. (2002). Survey research design. In *Research methods for managers* (3rd ed.) (pp. 97-122). Thousand Oaks, CA: Sage.

Leedy, P., & Ormrod, J. (2010). *Practical research: Planning and design* (9th ed.). Upper Saddle River, NJ: Prentice-Hall.

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

## u6 {.unnumbered}

Anderson, C. (2010). Presenting and evaluating qualitative research.
*American Journal of Pharmaceutical Education ,74* (8), 1-17. Retrieved from [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987281/pdf/ajpe141.pdf](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987281/pdf/ajpe141.pdf){target="_blank"}

Bogdan, R., & Biklen, S. (2007). *Qualitative research for education: An introduction to theories and method* (5th ed.). Boston, MA: Pearson.

Corbin, J., & Strauss, A. (2008). *Basics of qualitative research* (3rd ed.). Los Angeles, CA: Sage.

Gall, M., Gall, J., & Borg, W. (2007). *Educational research*. Boston, MA: Pearson.

Leedy, P. D., & Ormrod, J. E. (2010). *Practical research: Planning and design*. Upper Saddle River, NJ: Merrill.

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

## u7 {.unnumbered}

Leedy, P. & Ormrod, J. (2013). *Practical research: Planning and design* (10th ed.). Boston, MA: Pearson.

Molina-Azorín, J. F. & Cameron, R. (2015). History and emergent practices of multimethod and mixed methods in business research', in Hesse-Biber, S. & Johnson, R.B. (eds.), *Oxford handbook of multimethod and mixed methods research inquiry*, pp. 466-485, New York: Oxford University Press.

Rosch, D. M., Kniffin, L. E., & Guthrie, K. L. (2023). *Introduction to research in leadership*. Information Age Publishing.

::: {.content-visible when-format="docx"}
//todo
Prote: No reference for u8
:::